#!/bin/bash -x

function usage {
  echo "usage: pe-install <ubuntu|el>"
  exit 1
}

if [ 1 -ne "$#" ]; then
  usage
fi

case $1 in
  ubuntu)
    cd /tmp/pe && wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb && \
    dpkg -i puppetlabs-release-trusty.deb && \
    sed -i -e 's/^deb\-src /#deb-src /g' /etc/apt/sources.list && \
    apt-get update && apt-get -y upgrade && apt-get install -y puppet hiera
  ;;
  centos)
    rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm && \
    yum makecache && yum -y upgrade && yum install -y puppet hiera openssh-server
  ;;
  *)
    echo "Unknown OS: $1"
    usage
  ;; 
esac

if [ 0 == $? ]; then
  rm -rf /tmp/pe
fi

mkdir -p /usr/local/bin && ln -s /opt/puppet/bin /usr/local/bin/puppet
